spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.153.128:3306/chengxp?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456

# Logger Config
logging:
  level:
    com.cxp.springboot2mybatisplus: debug