spring:
  application:
    name: springboot2-admin-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 8822

info.groupId: @project.groupId@
info.artifactId: @project.artifactId@
info.version: @project.version@

#开启端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS